pages:
  image: aergus/latex
  before_script:
    # install the Libertinus fonts
  - wget "https://github.com/alerque/libertinus/releases/download/v7.040/Libertinus-7.040.zip"
  - unzip "Libertinus-7.040.zip"
  - mkdir -p /usr/share/fonts/opentype/libertinus
  - cp Libertinus-7.040/static/OTF/*.otf /usr/share/fonts/opentype/libertinus
    # Install IPA Mincho
  - apt-get --yes install fonts-ipafont-mincho
    # Refresh the font cache
  - fc-cache
  script:
    # load submodules
  - git submodule update --init --recursive
    # gitinfo2 for git information in the document
  - wget "https://raw.githubusercontent.com/Hightor/gitinfo2/CTAN/post-xxx-sample.txt" -O generate_gitinfo2
  - chmod +x generate_gitinfo2
  - ./generate_gitinfo2
    # building with latexmk, uses settings from .latexmkrc
  - latexmk
    # extract the results
  - mkdir public
  - mv main.pdf public/solutions-basic-category-theory.pdf
  artifacts:
    paths:
    - public
  only:
   - master

